/********************************************************************
* src/BaconDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/BaconDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableBaconDict();
extern void G__cpp_setup_inheritanceBaconDict();
extern void G__cpp_setup_typetableBaconDict();
extern void G__cpp_setup_memvarBaconDict();
extern void G__cpp_setup_globalBaconDict();
extern void G__cpp_setup_memfuncBaconDict();
extern void G__cpp_setup_funcBaconDict();
extern void G__set_cpp_environmentBaconDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "interface/BaconAnaDefs.hh"
#include "interface/TAddJet.hh"
#include "interface/TElectron.hh"
#include "interface/TElectron.hh~"
#include "interface/TEventInfo.hh"
#include "interface/TEventInfo.hh~"
#include "interface/TGenEventInfo.hh"
#include "interface/TGenParticle.hh"
#include "interface/TJet.hh"
#include "interface/TJet.hh~"
#include "interface/TMuon.hh"
#include "interface/TMuon.hh~"
#include "interface/TPFPart.hh"
#include "interface/TPhoton.hh"
#include "interface/TPhoton.hh~"
#include "interface/TTau.hh"
#include "interface/TTau.hh~"
#include "interface/TTrigger.hh"
#include "interface/TTrigger.hh~"
#include "interface/TVertex.hh"
#include "interface/TriggerRecord.hh"
#include "interface/TriggerRecord.hh~"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__BaconDictLN_TClass;
extern G__linked_taginfo G__BaconDictLN_TBuffer;
extern G__linked_taginfo G__BaconDictLN_TMemberInspector;
extern G__linked_taginfo G__BaconDictLN_TObject;
extern G__linked_taginfo G__BaconDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__BaconDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BaconDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__BaconDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BaconDictLN_bitsetlE128gR;
extern G__linked_taginfo G__BaconDictLN_bitsetlE256gR;
extern G__linked_taginfo G__BaconDictLN_baconhep;
extern G__linked_taginfo G__BaconDictLN_baconhepcLcLTAddJet;
extern G__linked_taginfo G__BaconDictLN_baconhepcLcLTElectron;
extern G__linked_taginfo G__BaconDictLN_baconhepcLcLEEleType;
extern G__linked_taginfo G__BaconDictLN_baconhepcLcLTEventInfo;
extern G__linked_taginfo G__BaconDictLN_baconhepcLcLTGenEventInfo;
extern G__linked_taginfo G__BaconDictLN_baconhepcLcLTGenParticle;
extern G__linked_taginfo G__BaconDictLN_baconhepcLcLTJet;
extern G__linked_taginfo G__BaconDictLN_baconhepcLcLTMuon;
extern G__linked_taginfo G__BaconDictLN_baconhepcLcLEMuType;
extern G__linked_taginfo G__BaconDictLN_baconhepcLcLEMuSelectorBit;
extern G__linked_taginfo G__BaconDictLN_baconhepcLcLTPFPart;
extern G__linked_taginfo G__BaconDictLN_baconhepcLcLTPhoton;
extern G__linked_taginfo G__BaconDictLN_baconhepcLcLEPhotonType;
extern G__linked_taginfo G__BaconDictLN_baconhepcLcLTTau;
extern G__linked_taginfo G__BaconDictLN_baconhepcLcLEHPSDiscriminator;
extern G__linked_taginfo G__BaconDictLN_pairlEstringcOunsignedsPintgR;
extern G__linked_taginfo G__BaconDictLN_vectorlEpairlEstringcOunsignedsPintgRcOallocatorlEpairlEstringcOunsignedsPintgRsPgRsPgR;
extern G__linked_taginfo G__BaconDictLN_reverse_iteratorlEvectorlEpairlEstringcOunsignedsPintgRcOallocatorlEpairlEstringcOunsignedsPintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BaconDictLN_vectorlEbaconhepcLcLTriggerRecordcOallocatorlEbaconhepcLcLTriggerRecordgRsPgR;
extern G__linked_taginfo G__BaconDictLN_reverse_iteratorlEvectorlEbaconhepcLcLTriggerRecordcOallocatorlEbaconhepcLcLTriggerRecordgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BaconDictLN_baconhepcLcLTVertex;

/* STUB derived class for protected member access */
